
export const ADD_LOGIN_ADMIN = "ADD_LOGIN_ADMIN"
export const GET_LOGIN_ADMIN="GET_LOGIN_ADMIN"


export const GET_USERS="GET_USERS"
export const DELETE_USERS="DELETE_USERS"
export const ADD_USERS="ADD_USER"
export const UPDATE_USERS="UPDATE_USERS"
export const GET_SINGLE_USER="GET_SINGLE_USER"



export const GET_EMPLOYEE_PAYROLL="GET_EMPLOYEE_PAYROLL"
export const DELETE_EMPLOYEE_PAYROLL="DELETE_EMPLOYEE_PAYROLL"
export const ADD_EMPLOYEE_PAYROLL="ADD_EMPLOYEE_PAYROLL"
export const UPDATE_EMPLOYEE_PAYROLL="UPDATE_EMPLOYEE_PAYROLL"
export const GET_SINGLE_EMPLOYEE_PAYROLL="GET_SINGLE_EMPLOYEE_PAYROLL"



export const GET_EMPLOYEE_INCREMENT="GET_EMPLOYEE_INCREMENT"
export const DELETE_EMPLOYEE_INCREMENT="DELETE_EMPLOYEE_INCREMENT"
export const ADD_EMPLOYEE_INCREMENT="ADD_EMPLOYEE_INCREMENT"
export const UPDATE_EMPLOYEE_INCREMENT="UPDATE_EMPLOYEE_INCREMENT"
export const GET_SINGLE_EMPLOYEE_INCREMENT="GET_SINGLE_EMPLOYEE_INCREMENT"

